-- CRIAÇÃO DAS TABELAS
CREATE TABLE PRODUTOS(
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	PRODUTO VARCHAR(32)
);

CREATE TABLE REGRAS(
	ID INTEGER,
	PRODUTO VARCHAR(32),
	PRIMARY KEY(ID, PRODUTO)
);

CREATE TABLE RECOMENDACAO(
	ID INTEGER,
	PRODUTO VARCHAR(32),
	PRIMARY KEY(ID),
	FOREIGN KEY(ID) REFERENCES REGRAS(ID)
);


-- INSERÇÃO DE PRODUTOS -- 
INSERT INTO PRODUTOS(PRODUTO) VALUES('Pão');
INSERT INTO PRODUTOS(PRODUTO) VALUES('Café');
INSERT INTO PRODUTOS(PRODUTO) VALUES('Leite');

-- INSERÇÃO DA 1ª REGRA --
INSERT INTO REGRAS(ID, PRODUTO) VALUES(1, 'Café');
INSERT INTO RECOMENDACAO(ID, PRODUTO) VALUES(1, 'Leite');

-- INSERÇÃO DA 2ª REGRA --
INSERT INTO REGRAS(ID, PRODUTO) VALUES(2, 'Café');
INSERT INTO REGRAS(ID, PRODUTO) VALUES(2, 'Leite');
INSERT INTO RECOMENDACAO(ID, PRODUTO) VALUES(2, 'Pão');
